import { NextRequest } from 'next/server';
import { getAuthUser, requirePermission } from '@/lib/auth-middleware';
import { successResponse, handleApiError } from '@/lib/api-response';
import { submitStockOpname } from '@/server/services/inventory.service';
import { Permissions } from '@/shared/constants';

/**
 * Authenticate the caller, enforce INVENTORY_OPNAME_CREATE permission, and submit the stock opname for the session identified by the route `id`.
 *
 * @param params - A promise resolving to route parameters; expects `{ id: string }` where `id` is the opname session identifier
 * @returns An HTTP Response containing a success payload on successful submission or an error response generated by the API error handler
 */
export async function POST(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { user } = await getAuthUser(request);
        requirePermission(user, Permissions.INVENTORY_OPNAME_CREATE);

        const { id } = await params;
        const sessionId = parseInt(id);

        await submitStockOpname(sessionId, user.id);

        return successResponse({ success: true, message: 'Stock opname submitted successfully' });
    } catch (error) {
        return handleApiError(error);
    }
}